### ISSUE TITLE
添加公众号菜单失败

### ISSUE THREAD

**Issue by iskycc** [songquanpeng/wechat-server#1]
已经在后台配置好token、appid、appscecret、EncodingAESKey，但是点击更新公众菜单报错：
`api unauthorized rid: 638f9019-32b25e9f-252ee1bd`

公众号已经可以获取到验证码，使用的是微信测试号，是有自定义菜单的权限的。
---------------------------------------------------------------------------------------------
早上再试的时候报错`错误：invalid credential, access_token is invalid or not latest rid: 638fd247-54ce3046-6b34e683`

我不理解

**Comment by songquanpeng** [comment]
第一次的报错是因为没有权限，按理说测试号确实不该这样。

第二次的报错看上去是因为 Access Token 没有正常刷新，这就很奇怪了，我现在还没办法复现这个问题。

我目前部署的版本是没有自定义菜单权限的微信个人公众号。

谢谢反馈。

**Comment by iskycc** [comment]
你说没办法复现我就想到了重启大法，一重启发现也解决了，那就没问题了

**Comment by songquanpeng** [comment]
这个确实需要重启服务，我忘记在 README 里说了。但是 Message Pusher 的最新版按理说是不需要的。

**Comment by thinker007** [comment]
没有自定义菜单权限的微信个人公众号 这个如何使用呢？

**Comment by lly-ke** [comment]
@thinker007 个人用不了, 需要微信认证才能获取接口权限

**Comment by ChangeYu0229** [comment]
重启docker后还是提示api unauthorized rid，是有自定义菜单权限的
