### ISSUE TITLE
使用 Docker 部署报错：dial tcp: lookup api.weixin.qq.com: device or resource busy

### ISSUE THREAD

**Issue by aiastia** [songquanpeng/wechat-server#3]
failed to refresh access token: Get "https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=***&secret=***": dial tcp: lookup api.weixin.qq.com: device or resource busy  

在主机上执行 curl  "https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=***&secret=***":“ 正常有回传

**Comment by songquanpeng** [comment]
之前 Message Pusher 那里也有人汇报过类似的问题：https://github.com/songquanpeng/message-pusher/issues/35

貌似和 Docker 的网络配置有关。

你运行其他容器会出现类似的问题吗？

**Comment by aiastia** [comment]
不会，其它的正常 我不用 docker 好像也不行 api unauthorized rid: 提示了这个

**Comment by songquanpeng** [comment]
直接用编译好的二进制文件也是报一样的错吗？

**Comment by aiastia** [comment]
不是  二进制 还没搞成果 配置了  Token AppID AppSecret EncodingAESKey  一刷新 这些 除了AppID 都没了  点 更新公众号菜单 就提示  api unauthorized rid:  

微信那边 点击提交 就提示 token 验证失败

**Comment by aiastia** [comment]
Root 用户微信 ID
 不知道是什么 就没填

**Comment by songquanpeng** [comment]
> 更新公众号菜单 就提示 api unauthorized rid:

这个是因为你的公众号没有使用 API 设置菜单的权限。

> Root 用户微信 ID

这个是超级管理员的微信 ID

**Comment by songquanpeng** [comment]
先关了，如果没有解决欢迎重开
