### ISSUE TITLE
能否支持部署下 zeabur  目前在zeabur 部署失败

### ISSUE THREAD

**Issue by tdouguo** [songquanpeng/wechat-server#6]

**Comment by public-cdn** [comment]
#0 building with "default" instance using docker driver

13:24:40

13:24:40#1 [internal] load .dockerignore

13:24:40#1 transferring context: 2B done

13:24:40#1 DONE 0.0s

13:24:40

13:24:40#2 [internal] load build definition from Dockerfile

13:24:40#2 transferring dockerfile: 3.85kB done

13:24:40#2 DONE 0.0s

13:24:40

13:24:40#3 [internal] load metadata for docker.io/library/golang:latest

13:24:42#3 ...

13:24:42

13:24:42#4 [internal] load metadata for docker.io/library/node:16

13:24:42#4 DONE 2.3s

13:24:42

13:24:42#3 [internal] load metadata for docker.io/library/golang:latest

13:24:42#3 DONE 2.4s

13:24:42

13:24:42#5 [internal] load metadata for docker.io/library/alpine:latest

13:24:42#5 DONE 2.5s

13:24:42

13:24:42#6 [internal] load build context

13:24:42#6 transferring context: 251.25kB 0.0s done

13:24:42#6 DONE 0.0s

13:24:42

13:24:42#7 [builder 2/6] WORKDIR /build

13:24:42#7 CACHED

13:24:42exit status 1

13:24:42

13:24:42#8 [builder 3/6] COPY ./web .

13:24:42#8 CACHED

13:24:42

13:24:42exit status 1

13:24:43#9 [builder 4/6] COPY ./VERSION .

13:24:43#9 ERROR: failed to calculate checksum of ref 1055f064-8f29-4c59-8842-5e55f4d490f0::n792sb85oeoyvdnhz6j8i67e3: "/VERSION": not found

zeabur 部署提示这个

**Comment by tdouguo** [comment]
17:44:07#3 ...

17:44:07

17:44:07#4 [internal] load metadata for docker.io/library/node:16

17:44:07#4 DONE 2.2s

17:44:08

17:44:08#3 [internal] load metadata for docker.io/library/golang:latest

17:44:08#3 DONE 2.4s

17:44:08

17:44:08#5 [internal] load metadata for docker.io/library/alpine:latest

17:44:08#5 DONE 2.4s

17:44:08

17:44:08#6 [internal] load build context

17:44:08#6 DONE 0.0s

17:44:08

17:44:08#7 [builder2 1/6] FROM docker.io/library/golang@sha256:ec457a2fcd235259273428a24e09900c496d0c52207266f96a330062a01e3622

17:44:08#7 resolve docker.io/library/golang@sha256:ec457a2fcd235259273428a24e09900c496d0c52207266f96a330062a01e3622 0.0s done

也没看到有什么错误 安装one-api 流程 fork 项目 部署 取消部署 设置环境变量 不行 但是one-api 是可以的

**Comment by songquanpeng** [comment]
修复了

**Comment by 1234-star** [comment]
依然无法部署。报错
--------------------

  23 |     COPY ./VERSION .

  24 |     RUN npm install

  25 | >>> RUN REACT_APP_VERSION=$(cat VERSION) npm run build

  26 |     

  27 |     FROM dockerhub.zeabur.cloud/library/golang AS builder2

--------------------

error: failed to solve: process "/bin/sh -c REACT_APP_VERSION=$(cat VERSION) npm run build" did not complete successfully: exit code: 1

Failed to build with zeaburpack: run buildctl build: exit status 1
