### ISSUE TITLE
初始密码无法更改

### ISSUE THREAD

**Issue by ivanberry** [songquanpeng/wechat-server#8]
<img width="342" alt="image" src="https://github.com/songquanpeng/wechat-server/assets/13112910/2443d0a8-7764-42d3-87ff-a5602728c250">

服务部署后，第一个事情是修改超级管理员账户密码，但是看起来不能修改。

**Comment by songquanpeng** [comment]
不要在 table 里进行修改，在个人页面修改

**Comment by ivanberry** [comment]
Thanks
